# Generated by Django 3.0.2 on 2020-01-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('surname', models.CharField(db_index=True, max_length=30)),
                ('lastName', models.CharField(blank=True, max_length=30)),
                ('dateBirth', models.DateTimeField()),
                ('email', models.EmailField(db_index=True, max_length=150, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(blank=True)),
                ('position', models.CharField(db_index=True, max_length=35)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='workersapp.Department')),
            ],
            options={
                'ordering': ['startDate'],
            },
        ),
    ]
