# Generated by Django 3.0.2 on 2020-01-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
